### PR TITLE
Add AFFiNE

### PR DESCRIPTION
**Pull request by TwilightSublime**
### Type

Addition 

---

### Changes

Adding AFFiNE to the list of notetaking apps
---

### Supporting Material

https://github.com/toeverything/affine
---

### Affiliation

None
---

### Checklist

- [ ✓] I have read the [Contributing](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) guide, and confirmed my PR aligns with the requirements
- [✓ ] I have performed a self-review (valid markdown formatting, spelling and grammar)
- [✓ ] I have indicated whether I have any affiliation with any software/ services added  
- [ ✓] I agree to follow the repositories [Contributor Covenant Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by A-childs-encyclopedia** [comment]
cc @Lissy93

**Review by Lissy93 — COMMENTED** [review]
Are you affiliated with the project in any capacity?

Edit: Sorry formatting of the PR body was a bit off, so I didn't see that you had completed that. Looks good

For future reference, please also use a more descriptive commit message (not `Update README.md`), as it makes tracking changes in the commit log easier.

**Review by Lissy93 — APPROVED** [review]
Aproved

**Comment by ltguillaume** [comment]
@Lissy93 I was looking for a somewhat richer alternative to Nextcloud Notes and found this, but what do you think about AFFiNE's current state?
- Privacy policy: https://affine.pro/privacy
- Their website is riddled with analytics:
  image
- These connections are made when working in an actual workspace (at least on app.affine.pro):
  image
- Their opt-out telemetry is enabled by default (https://github.com/toeverything/AFFiNE/issues/12821), even when self-hosting (https://github.com/toeverything/AFFiNE/issues/12465) or when visiting shared workspaces as an anonymous viewer (https://github.com/toeverything/AFFiNE/issues/12821). Even worse, opting out is _per browser_, not per user, and _after_ the first batch of data is already sent.

**Comment by Lissy93** [comment]
> @Lissy93 I was looking for a somewhat richer alternative to Nextcloud Notes and found this, but what do you think about AFFiNE's current state?

Yeah, that's not good.

Looks like in 2023 they received $18M in seed funding, and are now heavily backed by VC investors. And, a lot of that was from China.

Trust VC investors to ruin everything. And I expect things to get worse too, given their new direction is ✨AI✨

Even if opt-out was working, having tracking and analytics being on by default on the self-hosted version is never okay. I've submitted #524 to remove it.

Shame, as AFFiNE used to be good 😪

**Comment by ltguillaume** [comment]
Yikes, that list is so long... This is all (mostly?) automated, right? Wonder if you could do the same for https://anytype.io as I don't really have a good picture of it yet.

**Pull request merged**
