### PR TITLE
Replace OTR with XMPP clients with OMEMO (#94)

### PR DESCRIPTION
**Pull request by ltguillaume**
### Type

Addition / Removal

---

### Changes

See #94

__Please have a look at how I added a nested table__. While it is valid for Markdown to add plain HTML, this may be a no-go in your book?

---

### Supporting Material

See #94
---

### Affiliation

None
---

### Checklist

- [x] I have read the [Contributing](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) guide, and confirmed my PR aligns with the requirements
- [x] I have performed a self-review (valid markdown formatting, spelling and grammar)
- [x] I have indicated whether I have any affiliation with any software/ services added  
- [x] I agree to follow the repositories [Contributor Covenant Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by lissy93 — COMMENTED** [review]
Your comparison table is really useful, and don't personally mind the nested table, but with this additional info, maybe XMPP should have it's own section?

**Comment by ltGuillaume** [comment]
I'm not sure, really. Currently, there doesn't seem to be a protocol that has its own section, so that would put XMPP on a pedestal. So I propose to merge this first, especially because (judging from everything I've read about OTR) we would be doing people a disservice by recommending its use, and perhaps then talk more about how you would envision a separate section for XMPP?

**Comment by Lissy93** [comment]
That's fair. 
I think I need to do a big refactor at some point to make the list clearer, and re-test everything listed, so I'll revisit this then. But for now I'll merge this

**Comment by ltGuillaume** [comment]
Cool! Let me know what you think afterwards, we'll figure it out then 😃

**Comment by ltGuillaume** [comment]
Shouldn't the liss-bot have run already? I'd like to be sure that the table is correctly shown in the PDF output and on the website... 😅

**Pull request merged**
