### PR TITLE
Adds Olive to Bonus2-Video

### PR DESCRIPTION
**Pull request by i-penr**
### Type

Addition

---

### Changes

I've added Olive as a video editor to the list.

---

### Supporting Material

Here is the link I referenced: https://www.olivevideoeditor.org

---

### Affiliation

I am not associated with Olive in any way.

---

### Checklist

- [x] I have read the [Contributing](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) guide, and confirmed my PR aligns with the requirements
- [x] I have performed a self-review (valid markdown formatting, spelling and grammar)
- [x] I have indicated whether I have any affiliation with any software/ services added  
- [x] I agree to follow the repositories [Contributor Covenant Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by ltGuillaume** [comment]
Imho, isn't video editing enough of a hassle without using alpha software to do it? 😅 Even the most robust software for non-linear editing are known to crash more than once during a project, taking your progress down with it. So I wouldn't consider an editor in alpha stage a good suggestion for most people, if any at all 😟

**Comment by i-penr** [comment]
Yeah, I guess you are right. You decide if you want to merge this then :)

**Comment by ltGuillaume** [comment]
> Yeah, I guess you are right. You decide if you want to merge this then :)

Haha, that's not up to me 😉 Having had horrible experiences with non-linear video editing, I just wanted to put in my 2ct 🙈

**Comment by i-penr** [comment]
> 

Oh sorry, I thought you were a reviewer, haha

**Review by lissy93 — COMMENTED** [review]
Looks super cool, thanks for suggesting @i-penr :)

But lets wait until there's a stable release, as there's not currently an established install / update path for it yet, and although it does look to be actively maintained it's hard to be sure of the longevity of newer projects.

**Pull request closed without merging**
