### PR TITLE
Add Vikunja

### LINKED ISSUE #35: [ADDITION] Vikunja
### Category

Productivity

### Software to be added

Vikunja is an open-source to-do application (primarily web, there's also a very rudimentary flutter app and CalDAV integration). Similar to Todoist or Trello it lets you organize pretty much everything from a shopping list to a bigger project with multiple collaborators. A highlight are multiple views (List, Gantt, Table, Kanban) to visualize all tasks in different contexts. For collaboration, it has the usual sharing functionalities like team and user sharing but also Link Shares which allow you to share a list with someone else without them requiring an account.

### Supporting Material

Website: https://vikunja.io

### Association Disclosure

I am the creator of Vikunja.

### Would you like to submit a PR?

Yes!

### Please tick the boxes

- [X] You have filled out this form accurately, and to the best of your knowledge
- [X] You have indicated weather or not you are associated with the suggested addition
- [X] A similar submission has not already [been opened](https://github.com/Lissy93/awesome-privacy/issues?q=is%3Aissue) for this software/ service
- [X] You agree to the [code of conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by kolaente**
### Changes

This PR adds Vikunja, as proposed in #35.

Resolves #35 

### Supporting Material

Website: https://vikunja.io

### Affiliation

I am the creator of Vikunja.

### Checklist

- [x] I have read the [Contributing](/.github/CONTRIBUTING.md) guide, and confirmed my PR aligns with the requirements
- [x] I have performed a self-review (valid markdown formatting, spelling and grammar)
- [x] I have indicated whether I have any affiliation with any software/ services added  
- [x] I agree to follow the repositories [Contributor Covenant Code of Conduct](/.github/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by lissy93 — APPROVED** [review]
I think the description could be shortened a little, as too long and readers tend to just skip over. If possible aim for 1 or 2 sentences. 

I'm in the process of trying to shortened other entries, to be more objective and in line with other _awesome-list_ projects. 

That said, I'm happy to merge for now, and I can summarise later.

**Review by lissy93 — COMMENTED** [review]
Excuse any grammar formatting here, I'm on my phone ...

E.g. 

> it has the usual sharing functionalities like team and user sharing but also Link Shares which allow you to share a list with someone else without them requiring an account.

To just something like

_"sharing support via private team lists or public links"_


> to-do application. Similar to Todoist or Trello

In this context, i think people will understand what a todo app is without needing to mention examples like trello and todoist.

> it lets you organize pretty much everything from a shopping list to a bigger project with multiple collaborators. A highlight are multiple views (List, Gantt, Table, Kanban) to visualize all tasks in different contexts. 

Can maybe also be shortened a bit, and more to the point,  like

_"Suitable for organising variety of projects and tasks, supporting List, Gantt, Table and Kanban formats."_

**Comment by kolaente** [comment]
Thanks for the suggestions! I've incorporated and shortened the description of Vikunja a bit.

**Review by lissy93 — APPROVED** [review]

**Comment by kolaente** [comment]
:tada:

**Comment by Lissy93** [comment]
Thanks @kolaente  :) 
🔀 Merged!

**Pull request merged**
