### PR TITLE
Adds Budzet Zen to Budgeting Tools

### PR DESCRIPTION
**Pull request by BrunoBernardino**
(I've messed up the commit short message format, but you should be able to squash it with this PR's title -- if you want me to remake this PR anyway, I can).

### Type

Addition

---

### Changes

Budget Zen 2.0 is end-to-end encrypted via [userbase](https://userbase.com). You can read more about [that announcement here](https://news.onbrn.com/announcing-budget-zen-2.0-end-to-end-encrypted).

---

### Supporting Material

Budget Zen is Open Source (AGPL 3.0), and you can [view the source code in GitHub](https://github.com/BrunoBernardino/budgetzen-web).

---

### Affiliation

 I'm the author of [Budget Zen](https://budgetzen.net).

---

### Checklist

- [x] I have read the [Contributing](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CONTRIBUTING.md) guide, and confirmed my PR aligns with the requirements
- [x] I have performed a self-review (valid markdown formatting, spelling and grammar)
- [x] I have indicated whether I have any affiliation with any software/ services added  
- [x] I agree to follow the repositories [Contributor Covenant Code of Conduct](https://github.com/Lissy93/awesome-privacy/blob/main/.github/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by lissy93 — COMMENTED** [review]
Heya @BrunoBernardino 
Thanks for your contribution, and Zen Budget looks cool. 
You mentioned it was open source  (AGPL 3.0), but I couldn't find the code for the backend, where data is handled. Could you clarify whether it is actually open? Is it able to be self-hosted?

A few more questions,
- Are there any advantages over systems like [firefly-iii](https://github.com/firefly-iii/firefly-iii) ?
- I couldn't see if there was support for 2FA (OTP or U2F tokens), was I missing it?
- Is it easy for users to import or export data in a common format (I could only see proprietary JSON format)?

**Comment by BrunoBernardino** [comment]
Great questions @Lissy93, thanks!

It is able to be self-hosted, by virtue of the backend system it uses, [userbase.com](https://github.com/smallbets/userbase/) which is Open Source (MIT Licensed), so not as simple as changing an environment variable (but as easy as changing a couple of lines of code, to point to the self-hosted userbase version).

> Are there any advantages over systems like [firefly-iii](https://github.com/firefly-iii/firefly-iii) ?

I don't know Firefly III but it looks like a full-fledged personal finance manager, meaning it also tracks income, which Budget Zen doesn't (it's built to be a simple way of tracking expenses per budgets).

> I couldn't see if there was support for 2FA (OTP or U2F tokens), was I missing it?

[Userbase doesn't support it yet](https://github.com/smallbets/userbase/issues/324), but once it does, it can be built.

> Is it easy for users to import or export data in a common format (I could only see proprietary JSON format)?

The JSON format is [open and simple](https://budgetzen.net/import-export-file-format), but I don't offer CSV, for example, as it just hasn't been requested yet. I could consider it, if there's enough people requesting it.

**Review by lissy93 — APPROVED** [review]
Thanks for clarifying those details :)
Approved

**Comment by ltGuillaume** [comment]
>Userbase runs entirely on [Amazon Web Services](https://aws.amazon.com/), in the us-east-1 region. The availability of the Userbase service depends on [Amazon EC2](https://aws.amazon.com/ec2/), [Amazon S3](https://aws.amazon.com/s3/), and [Amazon DynamoDB](https://aws.amazon.com/dynamodb/)

Even if you want to run your own instance of Userbase, you _have_ to use AWS, as far as I can see...

@Lissy93

**Comment by BrunoBernardino** [comment]
@ltGuillaume indeed, the code is setup to connect to any AWS instance (can be on EU if you're "self-hosting"): https://github.com/smallbets/userbase/#configure-the-aws-credentials though you can arguably tweak it to use something else like DigitalOcean and MongoDB.

**Comment by BrunoBernardino** [comment]
@ltguillaume / @Lissy93 just an FYI, Budget Zen now doesn't depend on Userbase and is easier to self-host.

**Comment by ltguillaume** [comment]
@BrunoBernardino Nice! Can't have been easy to implement E2EE.

**Pull request merged**
